name: Deploy Documentation
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install mdBook
        run: cargo install mdbook --version 0.4.52

      - name: Install mdbook-admonish
        run: cargo install mdbook-admonish

      - name: Setup mdbook-admonish
        working-directory: docs
        run: mdbook-admonish install .

      - name: Build Book
        working-directory: docs
        run: mdbook build .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
